### ISSUE TITLE
Catchpoint blog migration

### ISSUE THREAD

**Issue by doffymingozzz** [zhoukekestar/notes#121]
Hi!

It’s Gleb from Catchpoint.com.

I've noticed that your website links to our old blog, which we’re currently migrating from a subdomain to the main domain. The reason I’m reaching out is to make sure you won’t have a 404 error on your website.

You have a link to our old blog on the following pages:
https://zhoukekestar.github.io/notes/2017/06/26/TCPIP-HTTP.html
I wonder if you’d be able to replace it with the new one:
https://www.catchpoint.com/blog/http-transaction-steps

Thanks for linking to Catchpoint.com!

Please don’t hesitate to contact me if something comes up v-gkapusto@catchpoint.com!

Best, 
Gleb

**Comment by zhoukekestar** [comment]
done, thanks for your reminding
