### ISSUE TITLE
笔记：阿里、网易、滴滴共十次前端面试碰到的问题

### ISSUE THREAD

**Issue by zhoukekestar** [zhoukekestar/notes#17]
http://zhoukekestar.github.io/notes/2017/06/07/interview-answers.html

**Comment by zhoukekestar** [comment]
讨论需要移步到issue~，欢迎一起修改文章答案

**Comment by mydaoyuan** [comment]
如何修改文章答案呀

**Comment by zhoukekestar** [comment]
* 点击`Edit this page` 按钮
  ![qq 20170611101854](https://user-images.githubusercontent.com/7157346/27007724-6b18bb22-4e8f-11e7-938c-2c90b50e672c.png)
* 点击`Edit this file` 按钮
![qq 20170611102109](https://user-images.githubusercontent.com/7157346/27007731-c0a7b48a-4e8f-11e7-8fb6-99e5893bd09b.png)
* 保存提交就行了（提交一个`Pull Request`，然后我这边`Merge`就行了）

**Comment by YAOHAO9** [comment]
数值字符串*1   数字性字符串-1
![image](https://user-images.githubusercontent.com/10281025/27018682-ca2c62f0-4f64-11e7-9369-016ef58a2c19.png)

**Comment by YAOHAO9** [comment]
![image](https://user-images.githubusercontent.com/10281025/27018721-053eeea8-4f65-11e7-9c02-f540af4f002d.png)

**Comment by zhoukekestar** [comment]
要这么说起来，我经常会用：
![qq 20170612115822](https://user-images.githubusercontent.com/7157346/27018943-dd85bdf4-4f66-11e7-8e54-7784cb51cb2d.png)

**Comment by tTc542** [comment]
`parseInt`还可以处理类似于`"12abc"`格式的字符串吧
```javascript
let pInt = str => {return ~~(str.match(/^\d*/)[0])}
```
