### ISSUE TITLE
怎么基于 Github 搭建自己的博客网站

### ISSUE THREAD

**Issue by zhoukekestar** [zhoukekestar/notes#25]
https://zhoukekestar.github.io/notes/2017/06/22/how-to-create-blog.html

**Comment by zhoukekestar** [comment]
看到#6  的需求，大概写了一下

**Comment by peterpanBest** [comment]
早上好 @zhoukekestar ！早上一打开电脑，进入您的 notes ，惊喜的发现您专门写一篇关于搭建 github blog 的文章  ，真是太惊喜了，已经收藏了这篇 blog ，仔细研究一下。在这里表示感谢，谢谢！
