### ISSUE TITLE
Weex 踩坑之 Gif 加载

### ISSUE THREAD

**Issue by zhoukekestar** [zhoukekestar/notes#34]

**Comment by CurrrryChen** [comment]
楼主，这样会导致image的border-radius失效啊

**Comment by zhoukekestar** [comment]
你可以尝试使用两个标签哈， 使用新标签（如 <Gif /> ) 标签来加载 gif 图片，这样就不会影响 image 原有标签的 css 属性了，如果你要让 Gif 支持 border-radius，那得自己实现一下了。😀
