### ISSUE TITLE
requirejs 源码浅析

### ISSUE THREAD

**Issue by zhoukekestar** [zhoukekestar/notes#35]

**Comment by zhoukekestar** [comment]
如何画UML，也可看一下[同事的分享](http://blog.csdn.net/lq83623/article/details/42478223)

**Comment by zhoukekestar** [comment]
webpack 原理的[浅析文章](http://www.cnblogs.com/yxy99/p/5852987.html)。

**Comment by zhoukekestar** [comment]
简要概括一下：

`requirejs` 主要步骤
* `require` 创建一个匿名模块，初始状态为 `fetched`, 因为能执行到该模块代码就说明资源已加载完毕
* 设置模块`callback` 为用户实际执行代码
* 开始 `load` 模块，并标记状态为 `loading`
* 遍历模块依赖，如果有未加载完成的模块，则执行加载动作
  * 加载过程中，资源初始状态为 `fetching`, 
  * 加载完成后为 `fetched` 状态
  * 执行`load`，`onload`，`executed`，`callback`返回对象
* 当模块依赖加载完成后，执行`onload`，状态改为 `loaded`
* 然后回调用户实际执行代码
* 执行完成后，状态更改为 `executed`

`seajs` 描述：
* 与 `requirejs`的主要特点是依赖的声明
* 一个预定义，一个执行中定义
  * 其中一个额外的操作就是去代码中正则匹配 `require` 关键字来获取依赖
* 一个预执行，一个后执行
  * 他们之间，在`onload`之前基本都是一样
  * 区别在于，`requirejs` 是`onload` 后，直接 `execute`，而 `seajs` 是在代码懒执行的，遇到`require` 才去`execute`

**Comment by gowk** [comment]
问下楼主博客链接里的流程图用什么软件画的？

**Comment by zhoukekestar** [comment]
Mac 下的 OmniGraffle 哈，如果是通用web 版的话，可以尝试用一下 [draw.io](http://draw.io)
