### ISSUE TITLE
caniuse

### ISSUE THREAD

**Issue by zhoukekestar** [zhoukekestar/notes#6]

**Comment by peterpanBest** [comment]
你好，在网上看到了您的 github blog ，里面的内容真的很棒， blog 也非常漂亮，请问您的 blog 是怎样搭建的呢？有没有相关的教程之类的，谢谢!

**Comment by zhoukekestar** [comment]
稍微写了一下，你可以看看。
https://zhoukekestar.github.io/notes/2017/06/22/how-to-create-blog.html

**Comment by peterpanBest** [comment]
看了呢，感谢前辈！smile ：D

在 2017-06-22 11:05:11，"keke" <notifications@github.com> 写道：


稍微写了一下，你可以看看。
https://zhoukekestar.github.io/notes/2017/06/22/how-to-create-blog.html
